-- MySQL Script generated by MySQL Workbench
-- 07/06/15 21:17:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema multimedios2.0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema multimedios2.0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `multimedios2.0` DEFAULT CHARACTER SET utf8 ;
USE `multimedios2.0` ;

-- -----------------------------------------------------
-- Table `multimedios2.0`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`cursos` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Sigla` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`niveles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`niveles` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`profesores` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido1` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`curso_nivel_profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`curso_nivel_profesor` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Cursos_Id` INT(11) NULL DEFAULT NULL,
  `Niveles_Id` INT(11) NULL DEFAULT NULL,
  `Profesores_Id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Curso_Nivel_Cursos1_idx` (`Cursos_Id` ASC),
  INDEX `fk_Curso_Nivel_Niveles1_idx` (`Niveles_Id` ASC),
  INDEX `fk_Curso_Nivel_Profesores1_idx` (`Profesores_Id` ASC),
  CONSTRAINT `fk_Curso_Nivel_Cursos1`
    FOREIGN KEY (`Cursos_Id`)
    REFERENCES `multimedios2.0`.`cursos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Nivel_Niveles1`
    FOREIGN KEY (`Niveles_Id`)
    REFERENCES `multimedios2.0`.`niveles` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Nivel_Profesores1`
    FOREIGN KEY (`Profesores_Id`)
    REFERENCES `multimedios2.0`.`profesores` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`padres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`padres` (
  `IdPadres` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido1` VARCHAR(30) NOT NULL,
  `Apellido2` VARCHAR(30) NOT NULL,
  `Identificacion` VARCHAR(30) NOT NULL,
  `Telefono` VARCHAR(30) NOT NULL,
  `Estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IdPadres`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`estudiantes` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdPadres` INT(11) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido1` VARCHAR(30) NOT NULL,
  `Apellido2` VARCHAR(30) NOT NULL,
  `Carnet` VARCHAR(30) NOT NULL,
  `Genero` VARCHAR(30) NOT NULL,
  `Estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdPadres_idx` (`IdPadres` ASC),
  CONSTRAINT `IdPadres`
    FOREIGN KEY (`IdPadres`)
    REFERENCES `multimedios2.0`.`padres` (`IdPadres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`secciones` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Seccion_Numero` VARCHAR(45) NOT NULL,
  `Niveles_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Secciones_Niveles1_idx` (`Niveles_Id` ASC),
  CONSTRAINT `fk_Secciones_Niveles1`
    FOREIGN KEY (`Niveles_Id`)
    REFERENCES `multimedios2.0`.`niveles` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`estudiantes_matriculados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`estudiantes_matriculados` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Ano` INT(11) NOT NULL,
  `Estudiantes_Id` INT(11) NOT NULL,
  `Secciones_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Estudiantes_Matriculados_Estudiantes_idx` (`Estudiantes_Id` ASC),
  INDEX `fk_Estudiantes_Matriculados_Secciones1_idx` (`Secciones_Id` ASC),
  CONSTRAINT `fk_Estudiantes_Matriculados_Estudiantes`
    FOREIGN KEY (`Estudiantes_Id`)
    REFERENCES `multimedios2.0`.`estudiantes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiantes_Matriculados_Secciones1`
    FOREIGN KEY (`Secciones_Id`)
    REFERENCES `multimedios2.0`.`secciones` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`ausencias_tardias_escapadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`ausencias_tardias_escapadas` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Estudiantes_Matriculados_Id` INT(11) NOT NULL,
  `Curso_Nivel_Id` INT(11) NOT NULL,
  `Tipo` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Ausencias_Tardias_Escapadas_Estudiantes_Matriculados1_idx` (`Estudiantes_Matriculados_Id` ASC),
  INDEX `fk_Ausencias_Tardias_Escapadas_Curso_Nivel1_idx` (`Curso_Nivel_Id` ASC),
  CONSTRAINT `fk_Ausencias_Tardias_Escapadas_Curso_Nivel1`
    FOREIGN KEY (`Curso_Nivel_Id`)
    REFERENCES `multimedios2.0`.`curso_nivel_profesor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ausencias_Tardias_Escapadas_Estudiantes_Matriculados1`
    FOREIGN KEY (`Estudiantes_Matriculados_Id`)
    REFERENCES `multimedios2.0`.`estudiantes_matriculados` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`notas` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Cotidiano` DOUBLE NULL DEFAULT NULL,
  `Parcial1` DOUBLE NULL DEFAULT NULL,
  `Parcial2` DOUBLE NULL DEFAULT NULL,
  `Final` DOUBLE NULL DEFAULT NULL,
  `Curso_Nivel_Id` INT(11) NULL DEFAULT NULL,
  `Estudiantes_Matriculados_Id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Notas_Curso_Nivel1_idx` (`Curso_Nivel_Id` ASC),
  INDEX `fk_Notas_Estudiantes_Matriculados1_idx` (`Estudiantes_Matriculados_Id` ASC),
  CONSTRAINT `fk_Notas_Curso_Nivel1`
    FOREIGN KEY (`Curso_Nivel_Id`)
    REFERENCES `multimedios2.0`.`curso_nivel_profesor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Estudiantes_Matriculados1`
    FOREIGN KEY (`Estudiantes_Matriculados_Id`)
    REFERENCES `multimedios2.0`.`estudiantes_matriculados` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `multimedios2.0`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multimedios2.0`.`usuarios` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserID` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido1` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NOT NULL,
  `Tipo` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
